ALTER TABLE sale_items
  ADD COLUMN IF NOT EXISTS item_type TEXT,
  ADD COLUMN IF NOT EXISTS item_color TEXT,
  ADD COLUMN IF NOT EXISTS weight_grams NUMERIC(12,3),
  ADD COLUMN IF NOT EXISTS print_time_hours NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS is_done BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS done_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS sale_items_is_done_idx ON sale_items(is_done);
